# ASP.NET Core (.NET Framework) & ReactJS (npm)
# Smart Library

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: "Restore NuGet"
  inputs:
    restoreSolution: '$(solution)'

- task: Npm@1
  displayName: "Restore NPM Package"
  inputs:
    command: 'install'
    workingDir: 'src\SmartLibrary.Web.FrontEnd'

- task: DotNetCoreCLI@2
  displayName: "Build Backend Application"
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: Npm@1
  displayName: "Build Frontend Application"
  inputs:
    command: 'custom'
    workingDir: 'src\SmartLibrary.Web.FrontEnd'
    customCommand: 'run build'

- task: DotNetCoreCLI@2
  displayName: "Unit Testing"
  inputs:
    command: 'test'
    projects: 'src/SmartLibrary.UnitTests'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/test_results/UnitTests/ /p:Exclude="[xunit.*]*'
    testRunTitle: 'Unit Testing'

- task: DotNetCoreCLI@2
  displayName: "Integration Testing"
  inputs:
    command: 'test'
    projects: 'src/SmartLibrary.Web.IntegrationTests'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/test_results/IntegrationTests/ /p:Exclude="[xunit.*]*'

- task: Npm@1
  displayName: "UI Testing"
  inputs:
    command: 'custom'
    workingDir: 'src\SmartLibrary.Web.FrontEnd'
    customCommand: 'npm run test:ci'

- task: reportgenerator@4
  displayName: "Create Coverage Report"
  inputs:
    reports: 'coverage.xml'
    targetdir: '$(Build.SourcesDirectory)/coveragereport'
    sourcedirs: '$(Build.SourcesDirectory)/test_results/IntegrationTests/;$(Build.SourcesDirectory)/test_results/UnitTests/;$(Build.SourcesDirectory)/test_results/UITests/'

- task: DotNetCoreCLI@2
  displayName: "Publish Application"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r win-x86 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifact"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SmartLibraryApp'
    publishLocation: 'Container'
